// <auto-generated />
using System;
using EdufyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AskAMuslimAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250427031637_UpdateDataSeeding")]
    partial class UpdateDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnectAPI.Models.Certificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgressId")
                        .IsUnique();

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("EdufyAPI.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "q1",
                            Category = 16,
                            Description = "Learn to memorize the Quran with effective techniques.",
                            InstructorId = "2c179b2d-1d3b-42a3-8d6f-d2fd86b73c29",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/q1.jpg",
                            Title = "Qur'an tafseer by Mufti menk"
                        },
                        new
                        {
                            Id = "q2",
                            Category = 16,
                            Description = "Master the basics of Tajweed for proper Quran recitation.",
                            InstructorId = "9a5c21b2-2d92-4d0f-bad3-47d4bbd4e611",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/q2.jpg",
                            Title = "Complete Quran Tafseer"
                        },
                        new
                        {
                            Id = "q3",
                            Category = 16,
                            Description = "Enhance your recitation skills with proper Makharij and Sifaat.",
                            InstructorId = "d1234567-89ab-4cde-8f01-23456789abcd",
                            Level = 2,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/q3.jpg",
                            Title = "TAFSEER OF QUR'AN |Sheikh Assim Al Hakeem"
                        },
                        new
                        {
                            Id = "q4",
                            Category = 16,
                            Description = "Dive deeper into Quranic understanding and reflection.",
                            InstructorId = "2c179b2d-1d3b-42a3-8d6f-d2fd86b73c29",
                            Level = 3,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/q4.jpg",
                            Title = "Mufti Menk - Quran Tafseer"
                        },
                        new
                        {
                            Id = "h1",
                            Category = 2,
                            Description = "Welcome to the **Comprehensive Hadith Course - Mishkat-ul-Masabih**...",
                            InstructorId = "9a5c21b2-2d92-4d0f-bad3-47d4bbd4e611",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/h1.jpg",
                            Title = "Comprehensive Hadith Course - Mishkat-ul-Masabih"
                        },
                        new
                        {
                            Id = "h2",
                            Category = 2,
                            Description = "The Free Advanced Diploma Course in Quran and Hadith...",
                            InstructorId = "9a5c21b2-2d92-4d0f-bad3-47d4bbd4e611",
                            Level = 3,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/h2.jpg",
                            Title = "Advanced Islamic Diploma Course in Quran and Hadith"
                        },
                        new
                        {
                            Id = "h3",
                            Category = 2,
                            Description = "An in-depth study of Sahih Bukhari collections.",
                            InstructorId = "f2345678-90ab-4def-9f12-34567890bcde",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/h3.jpg",
                            Title = "Hadith - Semester 1 | Shaykh Dr. Muhammad Salah"
                        },
                        new
                        {
                            Id = "h4",
                            Category = 2,
                            Description = "Study the top authentic Hadith books.",
                            InstructorId = "a3456789-01bc-4fgh-9g23-45678901cdef",
                            Level = 2,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/h4.jpg",
                            Title = "Al Nawawi's Forty Hadith"
                        },
                        new
                        {
                            Id = "a1",
                            Category = 4,
                            Description = "Learn the fundamentals of Islamic beliefs and Aqeedah.",
                            InstructorId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd66",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/a1.jpg",
                            Title = "principles of belief"
                        },
                        new
                        {
                            Id = "a2",
                            Category = 4,
                            Description = "Explore advanced topics in Islamic beliefs and theology.",
                            InstructorId = "a3456789-01bc-4fgh-9g23-45678901cdef",
                            Level = 3,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/a2.jpg",
                            Title = "Aqeedah/Creed"
                        },
                        new
                        {
                            Id = "a3",
                            Category = 4,
                            Description = "Study the beliefs of Ahlus Sunnah wal Jama'ah.",
                            InstructorId = "b4567890-12cd-5ghi-0h34-56789012def0",
                            Level = 2,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/a3.jpg",
                            Title = "Islamic Beliefs and Practices"
                        },
                        new
                        {
                            Id = "a4",
                            Category = 4,
                            Description = "Learn the fundamentals of Islamic beliefs and Aqeedah.",
                            InstructorId = "d1234567-89ab-4cde-8f01-23456789abcd",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/a4.jpg",
                            Title = "Fundamentals of Aqeedah"
                        },
                        new
                        {
                            Id = "f1",
                            Category = 3,
                            Description = "Learn the principles of Islamic law and jurisprudence.",
                            InstructorId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd66",
                            Level = 2,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/f1.jpg",
                            Title = "Fiqh Of Ramadan"
                        },
                        new
                        {
                            Id = "f2",
                            Category = 3,
                            Description = "Explore advanced topics in Islamic law and jurisprudence.",
                            InstructorId = "d1234567-89ab-4cde-8f01-23456789abcd",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/f2.jpg",
                            Title = "Fiqh - Semester 1 | Shaykh Assim Al-Hakeem"
                        },
                        new
                        {
                            Id = "f3",
                            Category = 3,
                            Description = "Study the principles of Islamic law and ethics.",
                            InstructorId = "d1234567-89ab-4cde-8f01-23456789abcd",
                            Level = 2,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/f3.jpg",
                            Title = "Islamic Fiqh"
                        },
                        new
                        {
                            Id = "f4",
                            Category = 3,
                            Description = "Learn the principles of Islamic law and jurisprudence.",
                            InstructorId = "b4567890-12cd-5ghi-0h34-56789012def0",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/f4.jpg",
                            Title = "FIQH IN ISLAM based on Sharh al-Umdah"
                        },
                        new
                        {
                            Id = "fa1",
                            Category = 17,
                            Description = "Learn the fundamentals of Islamic beliefs and Aqeedah.",
                            InstructorId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd66",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/fa1.jpg",
                            Title = "Faith in Islam"
                        },
                        new
                        {
                            Id = "fa2",
                            Category = 17,
                            Description = "Explore advanced topics in Islamic beliefs and theology.",
                            InstructorId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd66",
                            Level = 3,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/fa2.jpg",
                            Title = "The Six Articles of Faith in Islam"
                        },
                        new
                        {
                            Id = "fa3",
                            Category = 17,
                            Description = "Study the beliefs of Ahlus Sunnah wal Jama'ah.",
                            InstructorId = "d1234567-89ab-4cde-8f01-23456789abcd",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/fa3.jpg",
                            Title = "Islamic Faith"
                        },
                        new
                        {
                            Id = "fa4",
                            Category = 17,
                            Description = "Learn the fundamentals of Islamic beliefs and Aqeedah.",
                            InstructorId = "b4567890-12cd-5ghi-0h34-56789012def0",
                            Level = 1,
                            ThumbnailUrl = "https://ask-a-muslim.runasp.net/uploads/course-thumbnails/fa4.jpg",
                            Title = "Islamic Reminders"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Enrollment", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            CourseId = "q1"
                        },
                        new
                        {
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            CourseId = "q2"
                        },
                        new
                        {
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            CourseId = "q1"
                        },
                        new
                        {
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            CourseId = "q2"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = "l1q1",
                            Content = "This lesson discusses the virtues of memorizing the Quran and how it strengthens one’s connection with Allah.",
                            CourseId = "q1",
                            ExternalVideoUrl = "https://youtu.be/2qds-xNU4Xc?si=JOYbgc9mNGNWAosV",
                            ThumbnailUrl = "",
                            Title = "Quran Tafseer 1?",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2q1",
                            Content = "This lesson provides practical tips and techniques for starting the memorization journey.",
                            CourseId = "q1",
                            ExternalVideoUrl = "https://youtu.be/jRYb9NfNDZA?si=B3jkn9O3J6yZ9iN7",
                            ThumbnailUrl = "",
                            Title = "Quran Tafseer 2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1q2",
                            Content = "This lesson emphasizes the importance of consistency and setting realistic goals.",
                            CourseId = "q2",
                            ExternalVideoUrl = "https://youtu.be/d6hLVtnDSWQ?si=M2HFkEO5_XDg65GY",
                            ThumbnailUrl = "",
                            Title = "Principles of Tafseer - 1",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2q2",
                            Content = "This lesson discusses the significance of understanding the context and background of the verses.",
                            CourseId = "q2",
                            ExternalVideoUrl = "https://youtu.be/FY7yZhNw-XA?si=K7SElOuXowXvAmus",
                            ThumbnailUrl = "",
                            Title = "Principles of Tafseer - 2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1q3",
                            Content = "This lesson covers the importance of seeking knowledge from reliable sources.",
                            CourseId = "q3",
                            ExternalVideoUrl = "https://youtu.be/-qQNhf8tank?si=OKHub6BfIC0OVV2z",
                            ThumbnailUrl = "",
                            Title = "TAFSEER OF QUR'AN Ep 02 Sheikh Assim Al Hakeem",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2q3",
                            Content = "This lesson discusses the significance of understanding the Arabic language.",
                            CourseId = "q3",
                            ExternalVideoUrl = "https://youtu.be/1qh0G5uFVlw?si=4i_Y7J53XBOpyBVC",
                            ThumbnailUrl = "",
                            Title = "TAFSEER OF QUR'AN Ep 03 Surah Naba 1 4 Sheikh Assim Al Hakeem",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1q4",
                            Content = "This lesson emphasizes the importance of reflecting on the meanings of the verses.",
                            CourseId = "q4",
                            ExternalVideoUrl = "https://youtu.be/ZN9lzkWGA_E?si=KstXa-RsPxGSFgUZ",
                            ThumbnailUrl = "",
                            Title = "Mufti Menk - Quran Tafseer Day1",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2q4",
                            Content = "This lesson discusses the significance of memorizing and reciting the Quran regularly.",
                            CourseId = "q4",
                            ExternalVideoUrl = "https://youtu.be/2XMyXyLs1fc?si=wAAyLxgvWZtKqsQk",
                            ThumbnailUrl = "",
                            Title = "Mufti Menk - Quran Tafseer Day2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1h1",
                            Content = "This lesson covers the importance of seeking knowledge and its impact on personal growth.",
                            CourseId = "h1",
                            ExternalVideoUrl = "https://youtu.be/ZrrVbZhTqXk?si=4aoP0Y9tBPNfik8g",
                            ThumbnailUrl = "",
                            Title = "Principles of Hadith - 1",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2h1",
                            Content = "This lesson discusses the significance of sincerity in seeking knowledge.",
                            CourseId = "h1",
                            ExternalVideoUrl = "https://youtu.be/iQxLrk9y2pU?si=Kxi-qEFzjvvbZWCR",
                            ThumbnailUrl = "",
                            Title = "Principles of Hadith - 2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1h2",
                            Content = "This lesson emphasizes the importance of acting upon knowledge.",
                            CourseId = "h2",
                            ExternalVideoUrl = "https://youtu.be/x82aep1XRvw?si=nk5JJtk7I7K-o36t",
                            ThumbnailUrl = "",
                            Title = "Hadith 1",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2h2",
                            Content = "This lesson discusses the significance of sharing knowledge with others.",
                            CourseId = "h2",
                            ExternalVideoUrl = "https://youtu.be/w6ps627J2SA?si=tIMVfO7eaICOb7aB",
                            ThumbnailUrl = "",
                            Title = "Hadith 2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1h3",
                            Content = "This lesson covers the importance of humility in seeking knowledge.",
                            CourseId = "h3",
                            ExternalVideoUrl = "https://youtu.be/mWbG69wdO-Q?si=fXwrVbVi92JOdTHU",
                            ThumbnailUrl = "",
                            Title = "Hadith - Semester 1 - Introduction",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2h3",
                            Content = "This lesson discusses the significance of patience in the pursuit of knowledge.",
                            CourseId = "h3",
                            ExternalVideoUrl = "https://youtu.be/pJgBEUO_cu0?si=gKdL_UgVbzvt9TIN",
                            ThumbnailUrl = "",
                            Title = "Hadith - Semester 1 - Lecture 1 | Shaykh Dr. Muhammad Salah",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1h4",
                            Content = "This lesson emphasizes the importance of gratitude in seeking knowledge.",
                            CourseId = "h4",
                            ExternalVideoUrl = "https://youtu.be/rcsJ_RorUSs?si=CxqJPcqTNR198eIm",
                            ThumbnailUrl = "",
                            Title = "01-Explanation of the first hadith of intention for Ibn Uthaymeen",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2h4",
                            Content = "This lesson discusses the significance of perseverance in the face of challenges.",
                            CourseId = "h4",
                            ExternalVideoUrl = "https://youtu.be/yB0IK5iF5sI?si=9BPv146lsh6p-uLF",
                            ThumbnailUrl = "",
                            Title = "03-Explanation of the third Hadith ''Islam is built upon five'' by Ibn Uthaymeen",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1a1",
                            Content = "This lesson covers the importance of understanding the fundamentals of Aqeedah.",
                            CourseId = "a1",
                            ExternalVideoUrl = "https://youtu.be/mKF693FWc6A?si=IUg8K_Hcn82pCy1E",
                            ThumbnailUrl = "",
                            Title = "Principles of Belief: The Basis of rationale and proof",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2a1",
                            Content = "This lesson discusses the significance of Tawheed and its implications in daily life.",
                            CourseId = "a1",
                            ExternalVideoUrl = "https://youtu.be/urwR3bgRqB0?si=tUvMXeyr5WLdSXyG",
                            ThumbnailUrl = "",
                            Title = "Principles of Belief: MENTAL EVIDENCE IN ISLAM",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1a2",
                            Content = "This lesson emphasizes the importance of understanding the attributes of Allah.",
                            CourseId = "a2",
                            ExternalVideoUrl = "https://youtu.be/Ioy35ni7NXs?si=k6vVjInPQ6pkr1Rq",
                            ThumbnailUrl = "",
                            Title = "02 - Seeking a cure using specific Names of Allaah to treat a particular illness - Shaikh Uthaymeen",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2a2",
                            Content = "This lesson discusses the significance of belief in the Prophets and Messengers.",
                            CourseId = "a2",
                            ExternalVideoUrl = "https://youtu.be/wmnK6ZnXj7I?si=ugldutKHd0S1_Emf",
                            ThumbnailUrl = "",
                            Title = "03 - What does Al-‘Uboodiyyah (servitude: Oneness of Allah in worship) comprise of? Sh. Al-Uthaymeen\r\n",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1a3",
                            Content = "This lesson covers the importance of understanding the Day of Judgment.",
                            CourseId = "a3",
                            ExternalVideoUrl = "https://youtu.be/5bdrB9Gu_Y0?si=KVtWr4RArQJa6J_P",
                            ThumbnailUrl = "",
                            Title = "1 Explanation of the Islāmic Belief : Introduction",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2a3",
                            Content = "This lesson discusses the significance of belief in Angels.",
                            CourseId = "a3",
                            ExternalVideoUrl = "https://youtu.be/5fCEQBaHI28?si=Mi1VYzS8gq9ccNqx",
                            ThumbnailUrl = "",
                            Title = "2 Explanation of the Islāmic Belief:Praise of Allah",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1a4",
                            Content = "This lesson emphasizes the importance of understanding the concept of Shirk.",
                            CourseId = "a4",
                            ExternalVideoUrl = "https://youtu.be/2R0lqMBWzGE?si=EOCu9y3MtHRTbbys",
                            ThumbnailUrl = "",
                            Title = "The three Fundamental Principles (Thalaathat-ul-usool) Part 1 - Assim al hakeem",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2a4",
                            Content = "This lesson discusses the significance of belief in Divine Decree.",
                            CourseId = "a4",
                            ExternalVideoUrl = "https://youtu.be/1Rj5EtLGnKU?si=q595x4yKEz0sIMVj",
                            ThumbnailUrl = "",
                            Title = "The three Fundamental Principles (Thalaathat-ul-usool) Part 2 - Assim al hakeem",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1f1",
                            Content = "This lesson covers the importance of understanding the rules of prayer.",
                            CourseId = "f1",
                            ExternalVideoUrl = "https://youtu.be/TRq7E0gCe_w?si=AyJJpa4xsNBfuY65",
                            ThumbnailUrl = "",
                            Title = "What Is Fasting? | Fiqh Of Ramadan",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2f1",
                            Content = "This lesson discusses the significance of understanding the rules of fasting.",
                            CourseId = "f1",
                            ExternalVideoUrl = "https://youtu.be/aDK3sTkrOZE?si=sfQgMyI1tJWYZe3h",
                            ThumbnailUrl = "",
                            Title = "Do I Have to Make the Intention to Fast? | Fiqh of Ramadan",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1f2",
                            Content = "This lesson emphasizes the importance of understanding the rules of Zakat.",
                            CourseId = "f2",
                            ExternalVideoUrl = "https://youtu.be/V0tOuxRXgW8?si=KI0a2sRjiOdmWtJq",
                            ThumbnailUrl = "",
                            Title = "Fiqh - Semester 1 - Introduction",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2f2",
                            Content = "This lesson discusses the significance of understanding the rules of Hajj.",
                            CourseId = "f2",
                            ExternalVideoUrl = "https://youtu.be/Zxl94-DFGx4?si=Zd31VXLlRis6eMWF",
                            ThumbnailUrl = "",
                            Title = "Fiqh - Semester 1 - Lecture 1",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1f3",
                            Content = "This lesson covers the importance of understanding the rules of transactions.",
                            CourseId = "f3",
                            ExternalVideoUrl = "https://www.youtube.com/live/SNaabBT5hTw?si=Wi5SRFQdZHd7PF4f",
                            ThumbnailUrl = "",
                            Title = "Islamic Fiqh 13 - Assim al hakeem",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2f3",
                            Content = "This lesson discusses the significance of understanding the rules of contracts.",
                            CourseId = "f3",
                            ExternalVideoUrl = "https://www.youtube.com/live/opr8cfX6lSM?si=OdbdSheKXTXfi_qp",
                            ThumbnailUrl = "",
                            Title = "Islamic Fiqh 14 - Assim al hakeem",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1f4",
                            Content = "This lesson emphasizes the importance of understanding the rules of family matters.",
                            CourseId = "f4",
                            ExternalVideoUrl = "https://youtu.be/2DVTYk1jVE4?si=wv0RdDQM0Sjtz8N_",
                            ThumbnailUrl = "",
                            Title = "Sharh 'Umdah al-Fiqh 1 [Introduction-Ibn Qudamah]",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2f4",
                            Content = "This lesson discusses the significance of understanding the rules of inheritance.",
                            CourseId = "f4",
                            ExternalVideoUrl = "https://youtu.be/PJrknK2MZck?si=EF4dkX9mXtJefR4w",
                            ThumbnailUrl = "",
                            Title = "Sharh 'Umdah al-Fiqh 2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1fa1",
                            Content = "This lesson covers the importance of understanding the concept of faith.",
                            CourseId = "fa1",
                            ExternalVideoUrl = "https://youtu.be/pyUySSuyHNw?si=wKhwmoS9s5HidZyy",
                            ThumbnailUrl = "",
                            Title = "Faith Part 1",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2fa1",
                            Content = "This lesson discusses the significance of understanding the pillars of faith.",
                            CourseId = "fa1",
                            ExternalVideoUrl = "https://youtu.be/rLgfs2eBu3Y?si=Kpko5UiGDAIR9vZq",
                            ThumbnailUrl = "",
                            Title = "Faith Part 2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1fa2",
                            Content = "This lesson emphasizes the importance of understanding the concept of Tawheed.",
                            CourseId = "fa2",
                            ExternalVideoUrl = "https://youtu.be/foNaMDvYLPo?si=bkTPg4JXrV5_vsHp",
                            ThumbnailUrl = "",
                            Title = "What Are the Six Articles of Faith in Islam? | Pillars of Iman",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2fa2",
                            Content = "This lesson discusses the significance of understanding the concept of Shirk.",
                            CourseId = "fa2",
                            ExternalVideoUrl = "https://youtu.be/eKnIJqe8gc8?si=c6BpfWHl_Uv2g_K4",
                            ThumbnailUrl = "",
                            Title = "The Oneness of Allah in Islam: Tawheed and Monotheism",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1fa3",
                            Content = "This lesson covers the importance of understanding the concept of Iman.",
                            CourseId = "fa3",
                            ExternalVideoUrl = "https://youtu.be/VlQKUOIB8fM?si=QGIqI2wlEpALJd85",
                            ThumbnailUrl = "",
                            Title = "The Islamic faith # 1",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2fa3",
                            Content = "This lesson discusses the significance of understanding the concept of Kufr.",
                            CourseId = "fa3",
                            ExternalVideoUrl = "https://youtu.be/GKY3ycmTXZA?si=RQYWL0BpGa8WbOWN",
                            ThumbnailUrl = "",
                            Title = "The Islamic Faith # 2",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l1fa4",
                            Content = "This lesson emphasizes the importance of understanding the concept of Nifaq.",
                            CourseId = "fa4",
                            ExternalVideoUrl = "https://youtu.be/Z76LIk2fr6U?si=RsmZtJ0pSOn6fhR_",
                            ThumbnailUrl = "",
                            Title = "THIS SHOULD MAKE YOU CRY | Islamic Reminder",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "l2fa4",
                            Content = "This lesson discusses the significance of understanding the concept of Iman.",
                            CourseId = "fa4",
                            ExternalVideoUrl = "https://youtu.be/uioedvBAZb4?si=CjnPuUvnVSyJ1X41",
                            ThumbnailUrl = "",
                            Title = "Message to those who sell out their Deen",
                            VideoUrl = ""
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Progress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CompletedProgress")
                        .HasColumnType("bit");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalLessonsCompleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Answer", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<string>("SelectedOptionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId", "QuestionId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.HasIndex("SelectedOptionId")
                        .IsUnique();

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            QuestionId = "QUESTION-1",
                            SelectedOptionId = "OPTION-2"
                        },
                        new
                        {
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            QuestionId = "QUESTION-2",
                            SelectedOptionId = "OPTION-1"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Option", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = "OPTION-1",
                            IsCorrect = false,
                            OptionText = "3",
                            QuestionId = "QUESTION-1"
                        },
                        new
                        {
                            Id = "OPTION-2",
                            IsCorrect = true,
                            OptionText = "4",
                            QuestionId = "QUESTION-1"
                        },
                        new
                        {
                            Id = "OPTION-3",
                            IsCorrect = false,
                            OptionText = "5",
                            QuestionId = "QUESTION-1"
                        },
                        new
                        {
                            Id = "OPTION-4",
                            IsCorrect = false,
                            OptionText = "6",
                            QuestionId = "QUESTION-1"
                        },
                        new
                        {
                            Id = "OPTION-5",
                            IsCorrect = false,
                            OptionText = "Berlin",
                            QuestionId = "QUESTION-2"
                        },
                        new
                        {
                            Id = "OPTION-6",
                            IsCorrect = false,
                            OptionText = "Madrid",
                            QuestionId = "QUESTION-2"
                        },
                        new
                        {
                            Id = "OPTION-7",
                            IsCorrect = true,
                            OptionText = "Paris",
                            QuestionId = "QUESTION-2"
                        },
                        new
                        {
                            Id = "OPTION-8",
                            IsCorrect = false,
                            OptionText = "Rome",
                            QuestionId = "QUESTION-2"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = "QUESTION-1",
                            Marks = 5,
                            QuestionText = "What is 2 + 2?",
                            QuizId = "QUIZ-1"
                        },
                        new
                        {
                            Id = "QUESTION-2",
                            Marks = 95,
                            QuestionText = "What is the capital of France?",
                            QuizId = "QUIZ-1"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Quiz", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StudentQuizEvaluation")
                        .HasColumnType("int");

                    b.Property<int>("StudentQuizResult")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = "QUIZ-1",
                            Description = "A quiz to test your math skills.",
                            LessonId = "l1q1",
                            StudentQuizEvaluation = 0,
                            StudentQuizResult = 0,
                            Title = "Math Quiz",
                            TotalMarks = 100,
                            TotalQuestions = 2
                        },
                        new
                        {
                            Id = "QUIZ-2",
                            Description = "A quiz to test your science knowledge.",
                            LessonId = "l2q1",
                            StudentQuizEvaluation = 0,
                            StudentQuizResult = 0,
                            Title = "Science Quiz",
                            TotalMarks = 100,
                            TotalQuestions = 10
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Admin", b =>
                {
                    b.HasBaseType("EdufyAPI.Models.Roles.AppUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Instructor", b =>
                {
                    b.HasBaseType("EdufyAPI.Models.Roles.AppUser");

                    b.HasDiscriminator().HasValue("Instructor");

                    b.HasData(
                        new
                        {
                            Id = "626b8c7f-f4d4-4467-bb37-570f1aa6fd66",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-1",
                            Email = "aam@example.com",
                            EmailConfirmed = false,
                            FirstName = "AskAMuslim",
                            LastName = "Academy",
                            LockoutEnabled = false,
                            NormalizedEmail = "AAM@EXAMPLE.COM",
                            NormalizedUserName = "AAM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKsmLRBJp6I5tKPy0WDNs07ql09VZX8z4DGjbn3fzmT2LbzkPQnDg7czDSEiGsR3PA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-1",
                            TwoFactorEnabled = false,
                            UserName = "aam"
                        },
                        new
                        {
                            Id = "7d3f2475-7a1b-4f85-92eb-0faab6aa8d4f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-2",
                            Email = "marwan.mohamed@example.com",
                            EmailConfirmed = false,
                            FirstName = "Marwan",
                            LastName = "Mohamed",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARWAN.MOHAMED@EXAMPLE.COM",
                            NormalizedUserName = "MARWAN.MOHAMED",
                            PasswordHash = "AQAAAAIAAYagAAAAEKhfABcexVBa2CPOgHa7LU7h2tgaGe2VQbOMGe9uCcuVEb8tAwxqru9YHFTtJK3glw==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-2",
                            TwoFactorEnabled = false,
                            UserName = "marwan.mohamed"
                        },
                        new
                        {
                            Id = "9a5c21b2-2d92-4d0f-bad3-47d4bbd4e611",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-3",
                            Email = "mujahid.hussain@example.com",
                            EmailConfirmed = false,
                            FirstName = "Mujahid",
                            LastName = "Hussain",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUJAHID.HUSSAIN@EXAMPLE.COM",
                            NormalizedUserName = "MUJAHID.HUSSAIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKhfABcexVBa2CPOgHa7LU7h2tgaGe2VQbOMGe9uCcuVEb8tAwxqru9YHFTtJK3glw==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-3",
                            TwoFactorEnabled = false,
                            UserName = "mujahid.hussain"
                        },
                        new
                        {
                            Id = "2c179b2d-1d3b-42a3-8d6f-d2fd86b73c29",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-4",
                            Email = "mufti.menk@example.com",
                            EmailConfirmed = false,
                            FirstName = "Mufti",
                            LastName = "Menk",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUFTI.MENK@EXAMPLE.COM",
                            NormalizedUserName = "MUFTI.MENK",
                            PasswordHash = "AQAAAAIAAYagAAAAEKhfABcexVBa2CPOgHa7LU7h2tgaGe2VQbOMGe9uCcuVEb8tAwxqru9YHFTtJK3glw==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-4",
                            TwoFactorEnabled = false,
                            UserName = "mufti.menk"
                        },
                        new
                        {
                            Id = "d1234567-89ab-4cde-8f01-23456789abcd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-5",
                            Email = "assim.alhakeem@example.com",
                            EmailConfirmed = false,
                            FirstName = "Assim",
                            LastName = "AlHakeem",
                            LockoutEnabled = false,
                            NormalizedEmail = "ASSIM.ALHAKEEM@EXAMPLE.COM",
                            NormalizedUserName = "ASSIM.ALHAKEEM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1wXcGz8Hbl5otx+fN7ygtlzHv2NfqeUqlg3RW0dP4gWbTY6wHT0t8xKzJKzZfyDQ==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-5",
                            TwoFactorEnabled = false,
                            UserName = "assim.alhakeem"
                        },
                        new
                        {
                            Id = "f2345678-90ab-4def-9f12-34567890bcde",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-6",
                            Email = "muhammad.salah@example.com",
                            EmailConfirmed = false,
                            FirstName = "Muhammad",
                            LastName = "Salah",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUHAMMAD.SALAH@EXAMPLE.COM",
                            NormalizedUserName = "MUHAMMAD.SALAH",
                            PasswordHash = "AQAAAAIAAYagAAAAEC9oZk+QkS2u4GNHbAh9uPuBjNQfHdjkk5IvP8xCmUNz5cIY3ZoIXF1xv8bZf9nqBA==",
                            PhoneNumber = "0112233445",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-6",
                            TwoFactorEnabled = false,
                            UserName = "muhammad.salah"
                        },
                        new
                        {
                            Id = "a3456789-01bc-4fgh-9g23-45678901cdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-7",
                            Email = "ibn.uthaymeen@example.com",
                            EmailConfirmed = false,
                            FirstName = "Ibn",
                            LastName = "Uthaymeen",
                            LockoutEnabled = false,
                            NormalizedEmail = "IBN.UTHAYMEEN@EXAMPLE.COM",
                            NormalizedUserName = "IBN.UTHAYMEEN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDh4wGZKpAbvIJKliK8GLUUSUrfz1D7ySMf9IFXGwG3o8fR9cA7ek/5yk8QbMv9iyA==",
                            PhoneNumber = "0223344556",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-7",
                            TwoFactorEnabled = false,
                            UserName = "ibn.uthaymeen"
                        },
                        new
                        {
                            Id = "b4567890-12cd-5ghi-0h34-56789012def0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-8",
                            Email = "ibn.farooq@example.com",
                            EmailConfirmed = false,
                            FirstName = "Ibn",
                            LastName = "Farooq",
                            LockoutEnabled = false,
                            NormalizedEmail = "IBN.FAROOQ@EXAMPLE.COM",
                            NormalizedUserName = "IBN.FAROOQ",
                            PasswordHash = "AQAAAAIAAYagAAAAEDy4zHzmVDpQm3uvHQclPBfiD/NvWb8IlA6tbjdzGp5B0V5RBoTxAjB4vKnV8qvG8w==",
                            PhoneNumber = "0334455667",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-8",
                            TwoFactorEnabled = false,
                            UserName = "ibn.farooq"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Student", b =>
                {
                    b.HasBaseType("EdufyAPI.Models.Roles.AppUser");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-1",
                            Email = "ali.mahmoud@example.com",
                            EmailConfirmed = false,
                            FirstName = "Ali",
                            LastName = "Mahmoud",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.MAHMOUD@EXAMPLE.COM",
                            NormalizedUserName = "ALI.MAHMOUD",
                            PasswordHash = "AQAAAAIAAYagAAAAEKsmLRBJp6I5tKPy0WDNs07ql09VZX8z4DGjbn3fzmT2LbzkPQnDg7czDSEiGsR3PA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-1",
                            TwoFactorEnabled = false,
                            UserName = "ali.mahmoud"
                        },
                        new
                        {
                            Id = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-concurrency-stamp-2",
                            Email = "salma.ahmed@example.com",
                            EmailConfirmed = false,
                            FirstName = "Salma",
                            LastName = "Ahmed",
                            LockoutEnabled = false,
                            NormalizedEmail = "SALMA.AHMED@EXAMPLE.COM",
                            NormalizedUserName = "SALMA.AHMED",
                            PasswordHash = "AQAAAAIAAYagAAAAEKhfABcexVBa2CPOgHa7LU7h2tgaGe2VQbOMGe9uCcuVEb8tAwxqru9YHFTtJK3glw==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "fixed-security-stamp-2",
                            TwoFactorEnabled = false,
                            UserName = "salma.ahmed"
                        });
                });

            modelBuilder.Entity("EduConnectAPI.Models.Certificate", b =>
                {
                    b.HasOne("EdufyAPI.Models.Progress", "Progress")
                        .WithOne("Certificate")
                        .HasForeignKey("EduConnectAPI.Models.Certificate", "ProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("EdufyAPI.Models.Course", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EdufyAPI.Models.Enrollment", b =>
                {
                    b.HasOne("EdufyAPI.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EdufyAPI.Models.Lesson", b =>
                {
                    b.HasOne("EdufyAPI.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EdufyAPI.Models.Progress", b =>
                {
                    b.HasOne("EdufyAPI.Models.Course", "Course")
                        .WithMany("CourseProgress")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.Student", "Student")
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Enrollment", "Enrollment")
                        .WithOne("Progress")
                        .HasForeignKey("EdufyAPI.Models.Progress", "StudentId", "CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Answer", b =>
                {
                    b.HasOne("EdufyAPI.Models.QuizModels.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("EdufyAPI.Models.QuizModels.Answer", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.QuizModels.Option", "Option")
                        .WithOne("Answer")
                        .HasForeignKey("EdufyAPI.Models.QuizModels.Answer", "SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.Student", "Student")
                        .WithMany("Answers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Option", b =>
                {
                    b.HasOne("EdufyAPI.Models.QuizModels.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Question", b =>
                {
                    b.HasOne("EdufyAPI.Models.QuizModels.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Quiz", b =>
                {
                    b.HasOne("EdufyAPI.Models.Lesson", "Lesson")
                        .WithOne("Quiz")
                        .HasForeignKey("EdufyAPI.Models.QuizModels.Quiz", "LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.Course", b =>
                {
                    b.Navigation("CourseProgress");

                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EdufyAPI.Models.Enrollment", b =>
                {
                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.Lesson", b =>
                {
                    b.Navigation("Quiz")
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.Progress", b =>
                {
                    b.Navigation("Certificate")
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Option", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Question", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();

                    b.Navigation("Options");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Student", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Enrollments");

                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
