// <auto-generated />
using System;
using EdufyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdufyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnectAPI.Models.Certificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgressId")
                        .IsUnique();

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("EdufyAPI.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfStudentsEnrolled")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "1c700ea4-ac54-487f-80e4-25c7b348b9e0",
                            Description = "Learn the basics of C# programming, including syntax, OOP concepts, and best practices.",
                            InstructorId = "58ec4bbf-4913-4dc1-96b7-381159ce0878",
                            NumberOfStudentsEnrolled = 0,
                            ThumbnailUrl = "csharp_course_thumbnail.jpg",
                            Title = "Introduction to C#"
                        },
                        new
                        {
                            Id = "2d7df053-81d5-4bb8-994d-76619c341c46",
                            Description = "Deep dive into .NET framework, dependency injection, middleware, and microservices.",
                            InstructorId = "a86582e6-8511-4b78-b548-e17a2eaf0d3e",
                            NumberOfStudentsEnrolled = 0,
                            ThumbnailUrl = "dotnet_course_thumbnail.jpg",
                            Title = "Advanced .NET Development"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Enrollment", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            CourseId = "1c700ea4-ac54-487f-80e4-25c7b348b9e0"
                        },
                        new
                        {
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            CourseId = "2d7df053-81d5-4bb8-994d-76619c341c46"
                        },
                        new
                        {
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            CourseId = "1c700ea4-ac54-487f-80e4-25c7b348b9e0"
                        },
                        new
                        {
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            CourseId = "2d7df053-81d5-4bb8-994d-76619c341c46"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = "LESSON-1001",
                            Content = "This is the introduction to programming, covering the basics of coding.",
                            CourseId = "1c700ea4-ac54-487f-80e4-25c7b348b9e0",
                            ExternalVideoUrl = "https://example.com/intro-video",
                            ThumbnailUrl = "",
                            Title = "Introduction to Programming",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "LESSON-1002",
                            Content = "This lesson explains variables, constants, and different data types in programming.",
                            CourseId = "1c700ea4-ac54-487f-80e4-25c7b348b9e0",
                            ExternalVideoUrl = "https://example.com/variables-video",
                            ThumbnailUrl = "",
                            Title = "Variables and Data Types",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "LESSON-1003",
                            Content = "This lesson dives deep into sorting algorithms and their applications.",
                            CourseId = "2d7df053-81d5-4bb8-994d-76619c341c46",
                            ExternalVideoUrl = "https://example.com/algorithms-video",
                            ThumbnailUrl = "",
                            Title = "Advanced Algorithms",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "LESSON-1004",
                            Content = "Learn about trees, graphs, and their applications in computer science.",
                            CourseId = "2d7df053-81d5-4bb8-994d-76619c341c46",
                            ExternalVideoUrl = "https://example.com/data-structures-video",
                            ThumbnailUrl = "",
                            Title = "Data Structures: Trees and Graphs",
                            VideoUrl = ""
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Progress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalLessonsCompleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Progresses");

                    b.HasData(
                        new
                        {
                            Id = "PROG-1001",
                            CourseId = "1c700ea4-ac54-487f-80e4-25c7b348b9e0",
                            LastUpdated = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9151),
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            TotalLessonsCompleted = 5
                        },
                        new
                        {
                            Id = "PROG-1002",
                            CourseId = "1c700ea4-ac54-487f-80e4-25c7b348b9e0",
                            LastUpdated = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9165),
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            TotalLessonsCompleted = 7
                        },
                        new
                        {
                            Id = "PROG-1003",
                            CourseId = "2d7df053-81d5-4bb8-994d-76619c341c46",
                            LastUpdated = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9187),
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            TotalLessonsCompleted = 10
                        },
                        new
                        {
                            Id = "PROG-1004",
                            CourseId = "2d7df053-81d5-4bb8-994d-76619c341c46",
                            LastUpdated = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9192),
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            TotalLessonsCompleted = 12
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Answer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = "ANSWER-4001",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9498),
                            CreatedBy = "System",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = "QUESTION-3001",
                            Text = "Option A: Correct answer for question 1"
                        },
                        new
                        {
                            Id = "ANSWER-4002",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9501),
                            CreatedBy = "System",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = "QUESTION-3001",
                            Text = "Option B: Incorrect answer for question 1"
                        },
                        new
                        {
                            Id = "ANSWER-4003",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9503),
                            CreatedBy = "System",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = "QUESTION-3002",
                            Text = "Option A: Correct answer for question 2"
                        },
                        new
                        {
                            Id = "ANSWER-4004",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9507),
                            CreatedBy = "System",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = "QUESTION-3002",
                            Text = "Option B: Incorrect answer for question 2"
                        },
                        new
                        {
                            Id = "ANSWER-4005",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9509),
                            CreatedBy = "System",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = "QUESTION-3003",
                            Text = "Option A: Correct answer for question 3"
                        },
                        new
                        {
                            Id = "ANSWER-4006",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9512),
                            CreatedBy = "System",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = "QUESTION-3003",
                            Text = "Option B: Incorrect answer for question 3"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = "QUESTION-3001",
                            Answer = "Paris",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9428),
                            CreatedBy = "System",
                            Explanation = "The capital of France is Paris.",
                            OrderIndex = 1,
                            Points = 10,
                            QuizId = "QUIZ-2002",
                            Text = "What is the capital of France?",
                            Type = 1
                        },
                        new
                        {
                            Id = "QUESTION-3002",
                            Answer = "4",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9439),
                            CreatedBy = "System",
                            Explanation = "2 + 2 equals 4.",
                            OrderIndex = 2,
                            Points = 5,
                            QuizId = "QUIZ-2002",
                            Text = "What is 2 + 2?",
                            Type = 1
                        },
                        new
                        {
                            Id = "QUESTION-3003",
                            Answer = "George Orwell",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9442),
                            CreatedBy = "System",
                            Explanation = "The author of '1984' is George Orwell.",
                            OrderIndex = 1,
                            Points = 10,
                            QuizId = "QUIZ-2003",
                            Text = "Who is the author of '1984'?",
                            Type = 1
                        },
                        new
                        {
                            Id = "QUESTION-3004",
                            Answer = "Pacific Ocean",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9445),
                            CreatedBy = "System",
                            Explanation = "The largest ocean on Earth is the Pacific Ocean.",
                            OrderIndex = 2,
                            Points = 5,
                            QuizId = "QUIZ-2003",
                            Text = "What is the largest ocean on Earth?",
                            Type = 1
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Quiz", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = "QUIZ-2001",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9344),
                            CreatedBy = "System",
                            Description = "This quiz tests your knowledge on basic programming concepts.",
                            IsActive = true,
                            IsDeleted = false,
                            LessonId = "LESSON-1001",
                            PassingScore = 80,
                            TimeLimit = 300,
                            Title = "Introduction to Programming Quiz"
                        },
                        new
                        {
                            Id = "QUIZ-2002",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9348),
                            CreatedBy = "System",
                            Description = "This quiz tests your understanding of variables and data types.",
                            IsActive = true,
                            IsDeleted = false,
                            LessonId = "LESSON-1002",
                            PassingScore = 70,
                            TimeLimit = 300,
                            Title = "Variables and Data Types Quiz"
                        },
                        new
                        {
                            Id = "QUIZ-2003",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9353),
                            CreatedBy = "System",
                            Description = "This quiz evaluates your understanding of complex algorithms.",
                            IsActive = true,
                            IsDeleted = false,
                            LessonId = "LESSON-1003",
                            PassingScore = 85,
                            TimeLimit = 300,
                            Title = "Advanced Algorithms Quiz"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.QuizAttemp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgressId");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuizResults");

                    b.HasData(
                        new
                        {
                            Id = "QUIZATTEMPT-10001",
                            CompletedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9650),
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9636),
                            CreatedBy = "System",
                            ProgressId = "PROG-1001",
                            QuizId = "QUIZ-2001",
                            Score = 85.0,
                            StartedAt = new DateTime(2025, 4, 3, 3, 19, 53, 917, DateTimeKind.Utc).AddTicks(9641),
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f"
                        },
                        new
                        {
                            Id = "QUIZATTEMPT-10002",
                            CompletedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9657),
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9656),
                            CreatedBy = "System",
                            ProgressId = "PROG-1002",
                            QuizId = "QUIZ-2002",
                            Score = 60.0,
                            StartedAt = new DateTime(2025, 4, 3, 3, 14, 53, 917, DateTimeKind.Utc).AddTicks(9657),
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77"
                        },
                        new
                        {
                            Id = "QUIZATTEMPT-10003",
                            CompletedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9670),
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9667),
                            CreatedBy = "System",
                            ProgressId = "PROG-1001",
                            QuizId = "QUIZ-2002",
                            Score = 90.0,
                            StartedAt = new DateTime(2025, 4, 3, 3, 24, 53, 917, DateTimeKind.Utc).AddTicks(9669),
                            StudentId = "e452e625-327a-4bf2-9540-3db6577ab68f"
                        },
                        new
                        {
                            Id = "QUIZATTEMPT-10004",
                            CompletedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9755),
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9754),
                            CreatedBy = "System",
                            ProgressId = "PROG-1002",
                            QuizId = "QUIZ-2001",
                            Score = 75.0,
                            StartedAt = new DateTime(2025, 4, 3, 3, 9, 53, 917, DateTimeKind.Utc).AddTicks(9755),
                            StudentId = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.StudentAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnswerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuizResultId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SelectedAnswerIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmittedAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizResultId");

                    b.ToTable("StudentAnswer");

                    b.HasData(
                        new
                        {
                            Id = "STUDENTANSWER-7001",
                            AnswerId = "ANSWER-4001",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9855),
                            CreatedBy = "System",
                            IsCorrect = true,
                            QuestionId = "QUESTION-3001",
                            QuizResultId = "QUIZATTEMPT-10001",
                            SelectedAnswerIds = "[]",
                            SubmittedAnswer = "Option A: Correct answer for question 1",
                            SubmittedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9857)
                        },
                        new
                        {
                            Id = "STUDENTANSWER-7004",
                            AnswerId = "ANSWER-4002",
                            CreatedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9861),
                            CreatedBy = "System",
                            IsCorrect = false,
                            QuestionId = "QUESTION-3001",
                            QuizResultId = "QUIZATTEMPT-10002",
                            SelectedAnswerIds = "[]",
                            SubmittedAnswer = "Option B: Incorrect answer for question 1",
                            SubmittedAt = new DateTime(2025, 4, 3, 3, 34, 53, 917, DateTimeKind.Utc).AddTicks(9862)
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Admin", b =>
                {
                    b.HasBaseType("EdufyAPI.Models.Roles.AppUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Instructor", b =>
                {
                    b.HasBaseType("EdufyAPI.Models.Roles.AppUser");

                    b.HasDiscriminator().HasValue("Instructor");

                    b.HasData(
                        new
                        {
                            Id = "58ec4bbf-4913-4dc1-96b7-381159ce0878",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad4c8219-a15f-483e-bcf2-ce3d36fcb31d",
                            Email = "omar.tarek@example.com",
                            EmailConfirmed = false,
                            FirstName = "Omar",
                            LastName = "Tarek",
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR.TAREK@EXAMPLE.COM",
                            NormalizedUserName = "OMAR.TAREK",
                            PasswordHash = "AQAAAAIAAYagAAAAEN2pvhm7tzbFRycH1VwDB3mX5yYalkxT26LTDyF9Gh4osoT5CgBG3EIUFdVgnn6szQ==",
                            PhoneNumber = "1122334455",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "529502b7-6759-4bcb-a2a1-18f77f965c92",
                            TwoFactorEnabled = false,
                            UserName = "omar.tarek"
                        },
                        new
                        {
                            Id = "a86582e6-8511-4b78-b548-e17a2eaf0d3e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eb51ba1a-76f2-4143-9181-94bdafc40b5d",
                            Email = "hana.mostafa@example.com",
                            EmailConfirmed = false,
                            FirstName = "Hana",
                            LastName = "Mostafa",
                            LockoutEnabled = false,
                            NormalizedEmail = "HANA.MOSTAFA@EXAMPLE.COM",
                            NormalizedUserName = "HANA.MOSTAFA",
                            PasswordHash = "AQAAAAIAAYagAAAAEK6Wu+tVawuzWkP4DLqRx4Tnj6EAR0K8wXt2Wkro/6uHglTVTSQODeqjf6qyToUu4w==",
                            PhoneNumber = "5566778899",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "d76cf065-1170-4aa6-b14c-1799311fbe02",
                            TwoFactorEnabled = false,
                            UserName = "hana.mostafa"
                        });
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Student", b =>
                {
                    b.HasBaseType("EdufyAPI.Models.Roles.AppUser");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = "626b8c7f-f4d4-4467-bb37-570f1aa6fd77",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d8d9d936-2457-48b5-b025-a881a1b3cd65",
                            Email = "ali.mahmoud@example.com",
                            EmailConfirmed = false,
                            FirstName = "Ali",
                            LastName = "Mahmoud",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.MAHMOUD@EXAMPLE.COM",
                            NormalizedUserName = "ALI.MAHMOUD",
                            PasswordHash = "AQAAAAIAAYagAAAAEGtfl6cWHBXOVszeze9c1UOnW78PjjxeFNHzHqf80EBmfZkzPwgbbO/8awLc1bOcyg==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "ed34a4f1-508a-43b6-a959-480b443c4156",
                            TwoFactorEnabled = false,
                            UserName = "ali.mahmoud"
                        },
                        new
                        {
                            Id = "e452e625-327a-4bf2-9540-3db6577ab68f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3a56f72-071e-4622-b8d0-4541ef08e752",
                            Email = "salma.ahmed@example.com",
                            EmailConfirmed = false,
                            FirstName = "Salma",
                            LastName = "Ahmed",
                            LockoutEnabled = false,
                            NormalizedEmail = "SALMA.AHMED@EXAMPLE.COM",
                            NormalizedUserName = "SALMA.AHMED",
                            PasswordHash = "AQAAAAIAAYagAAAAECAip/M9N/yWzU+c5tXh1z2ZrEYOZR754UoOJuDoXrqboGKIDnbYq3rAsQLmJJCptw==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "",
                            SecurityStamp = "4674983e-ef83-4b01-8a7b-4b74a7707c4b",
                            TwoFactorEnabled = false,
                            UserName = "salma.ahmed"
                        });
                });

            modelBuilder.Entity("EduConnectAPI.Models.Certificate", b =>
                {
                    b.HasOne("EdufyAPI.Models.Progress", "Progress")
                        .WithOne("Certificate")
                        .HasForeignKey("EduConnectAPI.Models.Certificate", "ProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("EdufyAPI.Models.Course", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EdufyAPI.Models.Enrollment", b =>
                {
                    b.HasOne("EdufyAPI.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EdufyAPI.Models.Lesson", b =>
                {
                    b.HasOne("EdufyAPI.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EdufyAPI.Models.Progress", b =>
                {
                    b.HasOne("EdufyAPI.Models.Course", "Course")
                        .WithMany("CourseProgress")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.Student", null)
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Enrollment", "Enrollment")
                        .WithOne("Progress")
                        .HasForeignKey("EdufyAPI.Models.Progress", "StudentId", "CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Answer", b =>
                {
                    b.HasOne("EdufyAPI.Models.QuizModels.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Question", b =>
                {
                    b.HasOne("EdufyAPI.Models.QuizModels.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Quiz", b =>
                {
                    b.HasOne("EdufyAPI.Models.Lesson", "Lesson")
                        .WithOne("Quiz")
                        .HasForeignKey("EdufyAPI.Models.QuizModels.Quiz", "LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.QuizAttemp", b =>
                {
                    b.HasOne("EdufyAPI.Models.Progress", "Progress")
                        .WithMany("QuizAttemps")
                        .HasForeignKey("ProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.QuizModels.Quiz", "Quiz")
                        .WithMany("QuizResult")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.Student", "Student")
                        .WithMany("QuizAttemps")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Progress");

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.StudentAnswer", b =>
                {
                    b.HasOne("EdufyAPI.Models.QuizModels.Answer", "Answer")
                        .WithOne("StudentAnswer")
                        .HasForeignKey("EdufyAPI.Models.QuizModels.StudentAnswer", "AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.QuizModels.Question", "Question")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.QuizModels.QuizAttemp", "QuizResult")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuizResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("QuizResult");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EdufyAPI.Models.Roles.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.Course", b =>
                {
                    b.Navigation("CourseProgress");

                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EdufyAPI.Models.Enrollment", b =>
                {
                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.Lesson", b =>
                {
                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EdufyAPI.Models.Progress", b =>
                {
                    b.Navigation("Certificate")
                        .IsRequired();

                    b.Navigation("QuizAttemps");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Answer", b =>
                {
                    b.Navigation("StudentAnswer")
                        .IsRequired();
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizResult");
                });

            modelBuilder.Entity("EdufyAPI.Models.QuizModels.QuizAttemp", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EdufyAPI.Models.Roles.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Progresses");

                    b.Navigation("QuizAttemps");
                });
#pragma warning restore 612, 618
        }
    }
}
